/**
 * AutoCare360 seed script.
 *
 *   npm run seed                 → wipe + load catalog, demo/admin users, demo fleet & history
 *   npm run seed:catalog         → (re)load only vehicle types, fuel types, categories, templates
 *
 * The demo history is replayed through the real scheduling engine so every
 * status, due date, health score and chart is internally consistent.
 */
import '../config/env.js';
import fs from 'node:fs/promises';
import path from 'node:path';
import PDFDocument from 'pdfkit';
import mongoose from 'mongoose';
import { connectDB } from '../config/db.js';
import {
  User,
  VehicleType,
  FuelType,
  MaintenanceCategory,
  MaintenanceTemplate,
  Vehicle,
  MaintenanceTask,
  ServiceRecord,
  Expense,
  Document,
  Reminder,
  Notification,
} from '../models/index.js';
import { fuelTypes, vehicleTypes, categories } from './data/catalog.js';
import { templates } from './data/templates.js';
import { DEMO_USER, ADMIN_USER, demoFleet, extraUsers } from './data/demoFleet.js';
import { syncSchedule, completeTask, refreshVehicle, buildOccurrence } from '../services/scheduleService.js';
import { computeNextDue, evaluateTask } from '../services/maintenanceEngine.js';
import { processDueReminders, syncDocumentReminder } from '../services/reminderService.js';
import { uploadBuffer, UPLOAD_ROOT } from '../services/storageService.js';
import { isCloudinaryEnabled } from '../config/cloudinary.js';
import { addMonths } from '../utils/dates.js';

const NOW = new Date();
const DAY = 86400000;
const CATALOG_ONLY = process.argv.includes('--catalog-only');

// ─── Deterministic randomness ────────────────────────────────────────────────
function mulberry32(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const hashString = (s) => [...s].reduce((h, c) => Math.imul(31, h) + c.charCodeAt(0), 7) >>> 0;
const rand = mulberry32(360360);
const between = (a, b) => a + rand() * (b - a);
const randInt = (a, b) => Math.floor(between(a, b + 1));
const pick = (arr) => arr[Math.floor(rand() * arr.length)];
const roundTo = (n, step = 10) => Math.round(n / step) * step;
const round2 = (n) => Math.round(n * 100) / 100;
const monthsAgo = (m) => new Date(NOW.getTime() - m * 30.44 * DAY);
const daysFromNow = (d) => new Date(NOW.getTime() + d * DAY);
const step = (msg) => console.log(`\n▸ ${msg}`);
const info = (msg) => console.log(`  ${msg}`);

// ─── PDF helpers (sample documents & invoices) ──────────────────────────────
function pdfBuffer(draw) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    draw(doc);
    doc.end();
  });
}

const fmtDate = (d) => new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
const rs = (n) => `Rs. ${Number(n).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

function watermark(doc) {
  doc.save();
  doc.rotate(-30, { origin: [300, 420] });
  doc.font('Helvetica-Bold').fontSize(60).fillColor('#e2e8f0').opacity(0.55).text('SAMPLE', 90, 380, { width: 420, align: 'center' });
  doc.restore();
  doc.opacity(1);
}

function documentPdf({ title, issuer, number, holder, vehicle, issueDate, expiryDate }) {
  return pdfBuffer((doc) => {
    doc.rect(0, 0, doc.page.width, 90).fill('#0b1220');
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(18).text(issuer, 50, 30);
    doc.font('Helvetica').fontSize(10).fillColor('#93c5fd').text('Demo document generated by AutoCare360', 50, 56);
    watermark(doc);
    doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(20).text(title, 50, 130);
    const rows = [
      ['Document number', number],
      ['Issued to', holder],
      ['Vehicle', vehicle || '—'],
      ['Issue date', issueDate ? fmtDate(issueDate) : '—'],
      ['Valid until', expiryDate ? fmtDate(expiryDate) : 'No expiry'],
    ];
    let y = 180;
    for (const [k, v] of rows) {
      doc.font('Helvetica').fontSize(10).fillColor('#64748b').text(k.toUpperCase(), 50, y);
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#0f172a').text(v, 50, y + 14);
      y += 48;
    }
    doc.font('Helvetica-Oblique').fontSize(9).fillColor('#94a3b8').text('This is a sample document for demonstration purposes only and has no legal validity.', 50, 720, { width: 495, align: 'center' });
  });
}

function invoicePdf({ center, location, invoiceNo, date, vehicleLabel, odometer, unit, parts, labour, taxes, discount, total }) {
  return pdfBuffer((doc) => {
    doc.rect(0, 0, doc.page.width, 90).fill('#0b1220');
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(17).text(center, 50, 28);
    doc.font('Helvetica').fontSize(10).fillColor('#93c5fd').text(location, 50, 54);
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(12).text('TAX INVOICE', 380, 32, { width: 165, align: 'right' });
    doc.font('Helvetica').fontSize(9).fillColor('#cbd5e1').text(`${invoiceNo} · ${fmtDate(date)}`, 380, 52, { width: 165, align: 'right' });
    watermark(doc);
    doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(11).text(vehicleLabel, 50, 115);
    doc.font('Helvetica').fontSize(9).fillColor('#64748b').text(`Odometer: ${odometer.toLocaleString('en-IN')} ${unit}`, 50, 132);

    let y = 165;
    doc.rect(50, y, 495, 22).fill('#f1f5f9');
    doc.fillColor('#334155').font('Helvetica-Bold').fontSize(9);
    doc.text('DESCRIPTION', 58, y + 7);
    doc.text('QTY', 360, y + 7, { width: 40, align: 'right' });
    doc.text('AMOUNT', 450, y + 7, { width: 87, align: 'right' });
    y += 30;
    doc.font('Helvetica').fontSize(9.5).fillColor('#0f172a');
    for (const p of parts) {
      doc.text(p.name, 58, y, { width: 290 });
      doc.text(String(p.quantity), 360, y, { width: 40, align: 'right' });
      doc.text(rs(p.quantity * p.unitPrice), 450, y, { width: 87, align: 'right' });
      y += 20;
    }
    doc.text('Labour & workshop charges', 58, y);
    doc.text(rs(labour), 450, y, { width: 87, align: 'right' });
    y += 30;
    const lines = [['GST', taxes], ...(discount ? [['Discount', -discount]] : []), ['Total', total]];
    for (const [k, v] of lines) {
      doc.font(k === 'Total' ? 'Helvetica-Bold' : 'Helvetica').fontSize(k === 'Total' ? 12 : 10);
      doc.text(k, 330, y, { width: 110, align: 'right' });
      doc.text(rs(v), 450, y, { width: 87, align: 'right' });
      y += 20;
    }
    doc.font('Helvetica-Oblique').fontSize(9).fillColor('#94a3b8').text('Sample invoice generated for the AutoCare360 demo.', 50, 740, { width: 495, align: 'center' });
  });
}

// ─── Catalog ─────────────────────────────────────────────────────────────────
async function seedCatalog() {
  step('Loading catalog');
  await Promise.all([
    FuelType.deleteMany({}),
    VehicleType.deleteMany({}),
    MaintenanceCategory.deleteMany({}),
    MaintenanceTemplate.deleteMany({}),
  ]);
  await FuelType.insertMany(fuelTypes);
  await VehicleType.insertMany(vehicleTypes);
  const cats = await MaintenanceCategory.insertMany(categories);
  const catId = Object.fromEntries(cats.map((c) => [c.code, c._id]));
  const docs = templates.map((t) => {
    if (!catId[t.category]) throw new Error(`Unknown category "${t.category}" in template ${t.code}`);
    return { ...t, category: catId[t.category] };
  });
  await MaintenanceTemplate.insertMany(docs);
  info(`${fuelTypes.length} fuel types · ${vehicleTypes.length} vehicle types · ${categories.length} categories · ${docs.length} templates`);
}

// ─── Usage model (odometer / hour-meter over time) ──────────────────────────
function buildUsageModel(def) {
  const start = new Date(def.vehicle.purchaseDate);
  const days = Math.max(1, Math.ceil((NOW - start) / DAY));
  const local = mulberry32(hashString(def.key));
  const cumulative = new Float64Array(days + 1);
  let total = 0;
  for (let i = 0; i <= days; i += 1) {
    const d = new Date(start.getTime() + i * DAY);
    let w = def.seasonal ? def.seasonal[d.getMonth()] : 1;
    w *= 0.7 + local() * 0.6;
    if (!def.seasonal && d.getDay() === 0) w *= def.vehicle.vehicleType === 'commercial_vehicle' ? 0.15 : 1.35;
    total += w;
    cumulative[i] = total;
  }
  const base = def.vehicle.purchaseOdometer || 0;
  const span = def.currentOdometer - base;
  return (date) => {
    const i = Math.max(0, Math.min(days, Math.floor((new Date(date) - start) / DAY)));
    return Math.round(base + (span * cumulative[i]) / total);
  };
}

// ─── Service simulation helpers ─────────────────────────────────────────────
const LABOUR_ONLY = /(inspection|check|scan|report|update|adjust|test|top-up|rotation|alignment|balancing|greasing|lubrication|cleaning|diagnostics|free-play)/i;

function buildInvoiceLines(tasks, make, group) {
  const parts = [];
  let labour = group === 'two_wheeler' ? 350 : ['heavy_commercial', 'agricultural', 'light_commercial'].includes(group) ? 1200 : 850;
  for (const t of tasks) {
    const cost = (t.estimatedCost || 0) * between(0.9, 1.12);
    if (!cost) continue;
    if (LABOUR_ONLY.test(t.name)) {
      labour += cost;
    } else {
      parts.push({
        name: t.name.replace(/\s+(replacement|change)\b/i, '').replace(/\s*\([^)]*\)$/, ''),
        partNumber: `${make.replace(/[^A-Za-z]/g, '').slice(0, 3).toUpperCase()}-${String(hashString(t.code) % 90000 + 10000)}`,
        quantity: 1,
        unitPrice: roundTo(cost * 0.72, 5),
      });
      labour += cost * 0.28;
    }
  }
  return { parts, labour: roundTo(labour, 10) };
}

const TASK_FIELDS = [
  'template',
  'code',
  'name',
  'description',
  'category',
  'priority',
  'serviceMode',
  'isRecurring',
  'isCustom',
  'intervalKm',
  'intervalMonths',
  'estimatedCost',
  'estimatedDurationMinutes',
];
const taskFields = (task) => Object.fromEntries(TASK_FIELDS.map((f) => [f, task[f]]));

async function skipAt(task, vehicle, date, odometer, reason) {
  task.status = 'skipped';
  task.isOpen = false;
  task.dueBy = null;
  task.skippedAt = date;
  task.skipReason = reason;
  await task.save();
  const draft = buildOccurrence(taskFields(task), {
    vehicle: { _id: vehicle._id, owner: vehicle.owner, odometer },
    lastDate: date,
    lastOdometer: odometer,
    now: date,
  });
  await MaintenanceTask.create(draft);
}

const unitFor = (typeCode) => (vehicleTypes.find((t) => t.code === typeCode)?.usageUnit === 'hours' ? 'hrs' : 'km');
const groupFor = (typeCode) => vehicleTypes.find((t) => t.code === typeCode)?.group;

async function simulateService(owner, vehicle, def, event, odoAt, invoiceCounter) {
  const date = monthsAgo(event.monthsAgo);
  const odometer = odoAt(date);
  await Vehicle.updateOne({ _id: vehicle._id }, { $set: { odometer } });

  const open = await MaintenanceTask.find({ vehicle: vehicle._id, isOpen: true });
  let selected;
  if (event.only) {
    selected = open.filter((t) => event.only.includes(t.code));
  } else {
    selected = open.filter((t) => {
      if (event.leave?.includes(t.code)) return false;
      const { status, progress } = evaluateTask(t, { currentOdometer: odometer, now: date });
      if (event.minor) return status !== 'up_to_date';
      // Workshops also do items that are close to due while the vehicle is in.
      return status !== 'up_to_date' || progress >= 0.7;
    });
  }

  const group = groupFor(def.vehicle.vehicleType);
  const { parts, labour } = buildInvoiceLines(selected, def.vehicle.make, group);
  const allParts = [...parts, ...(event.extraParts || [])];
  const partsCost = allParts.reduce((s, p) => s + p.quantity * p.unitPrice, 0);
  const taxes = roundTo((partsCost + labour) * 0.18, 1);
  const discount = rand() < 0.3 ? roundTo((partsCost + labour) * 0.05, 10) : 0;

  const record = await ServiceRecord.create({
    owner,
    vehicle: vehicle._id,
    serviceDate: date,
    odometer,
    serviceCenter: event.center,
    serviceCenterLocation: event.location,
    mechanic: event.mechanic,
    serviceType: event.type || (event.minor ? 'inspection' : 'periodic_service'),
    maintenanceItems: selected.map((t) => ({ task: t._id, code: t.code, name: t.name, category: t.category })),
    partsReplaced: allParts,
    laborCost: labour,
    taxes,
    discount,
    rating: event.rating,
    notes:
      event.notes ||
      pick([
        'Routine service completed. Vehicle washed and vacuumed.',
        'All fluids topped up. No major issues found.',
        'Service done as per schedule. Advised to monitor tyre wear.',
        'General check-up completed; road test OK.',
      ]),
  });

  const perItem = selected.length ? round2(record.totalCost / selected.length) : undefined;
  for (const task of selected) {
    await completeTask(task, { date, odometer, cost: perItem, serviceRecord: record._id, refresh: false, now: date });
  }

  const invoiceNo = `INV-${date.getFullYear()}-${String(invoiceCounter).padStart(5, '0')}`;
  const buffer = await invoicePdf({
    center: event.center,
    location: event.location,
    invoiceNo,
    date,
    vehicleLabel: `${def.vehicle.make} ${def.vehicle.model} · ${def.vehicle.registrationNumber}`,
    odometer,
    unit: unitFor(def.vehicle.vehicleType),
    parts: allParts,
    labour,
    taxes,
    discount,
    total: record.totalCost,
  });
  record.invoice = await uploadBuffer(buffer, { originalName: `${invoiceNo}.pdf`, mimeType: 'application/pdf', folder: 'invoices' });

  if (record.totalCost > 0) {
    const expense = await Expense.create({
      owner,
      vehicle: vehicle._id,
      category: record.serviceType === 'repair' ? 'repairs' : record.serviceType === 'tyre_service' ? 'tyres' : 'maintenance',
      amount: record.totalCost,
      date,
      odometer,
      description: `${record.serviceType === 'repair' ? 'Repair' : record.serviceType === 'tyre_service' ? 'Tyre service' : 'Periodic service'} · ${event.center}`,
      vendor: event.center,
      paymentMethod: pick(['card', 'upi', 'upi']),
      serviceRecord: record._id,
    });
    record.expense = expense._id;
  }
  await record.save();
  return { record, completed: selected.length, date, odometer };
}

async function simulateDiy(owner, vehicle, date, odometer) {
  await Vehicle.updateOne({ _id: vehicle._id }, { $set: { odometer } });
  // DIY items plus short-interval checks anyone can do (e.g. monthly fleet walk-arounds).
  const open = await MaintenanceTask.find({
    vehicle: vehicle._id,
    isOpen: true,
    $or: [{ serviceMode: 'diy' }, { serviceMode: 'either', intervalMonths: { $lte: 3 } }],
  });
  let done = 0;
  for (const task of open) {
    const { status } = evaluateTask(task, { currentOdometer: odometer, now: date });
    if (status === 'up_to_date') continue;
    if (rand() < 0.1 && task.priority !== 'high') {
      await skipAt(task, vehicle, date, odometer, 'Checked — still in good condition');
    } else {
      const cost = task.estimatedCost ? roundTo(task.estimatedCost * between(0.8, 1.1)) : undefined;
      await completeTask(task, { date, odometer, cost, notes: 'Done at home', refresh: false, now: date });
      if (cost) {
        await Expense.create({
          owner,
          vehicle: vehicle._id,
          category: task.name.toLowerCase().includes('tyre') ? 'tyres' : 'parts',
          amount: cost,
          date,
          odometer,
          description: task.name,
          vendor: 'DIY',
          paymentMethod: 'upi',
        });
      }
    }
    done += 1;
  }
  return done;
}

// ─── Running-cost expenses ───────────────────────────────────────────────────
const FUEL_VENDORS = {
  petrol: ['Indian Oil — Baner Road', 'HP Petrol Pump — Wakad', 'Bharat Petroleum — Aundh', 'Nayara Energy — Hinjewadi'],
  diesel: ['Indian Oil — Chakan MIDC', 'HP Petrol Pump — Bhosari', 'Bharat Petroleum — Moshi', 'IOCL — Baramati Road'],
  cng: ['MNGL CNG Station — Baner', 'MNGL CNG Station — Balewadi', 'MNGL CNG Station — Pashan'],
  charging: ['Home charging (MSEDCL)'],
  dc: ['DC fast charger — Mumbai-Pune Expressway', 'DC fast charger — Phoenix Marketcity', 'DC fast charger — Hinjewadi Phase 2'],
};

function fuelEntry({ owner, vehicle, date, odometer, unit, qty, price, vendor, category, fullTank }) {
  return {
    owner,
    vehicle,
    category,
    amount: round2(qty * price),
    date,
    odometer,
    description: category === 'charging' ? `Charging · ${qty.toFixed(1)} kWh` : `${unit === 'kg' ? 'CNG' : 'Fuel'} · ${qty.toFixed(1)} ${unit}`,
    vendor,
    paymentMethod: pick(['upi', 'upi', 'card', 'wallet']),
    fuelDetails: { quantity: round2(qty), unit, pricePerUnit: round2(price), fullTank },
  };
}

function runningCosts(owner, vehicleId, def, odoAt, windowStart) {
  const entries = [];
  const f = def.fuel;
  const x = def.extras;
  const monthsSpan = Math.ceil((NOW - windowStart) / (30.44 * DAY));
  for (let m = monthsSpan; m >= 0; m -= 1) {
    const from = new Date(Math.max(windowStart.getTime(), monthsAgo(m + 1).getTime()));
    const to = new Date(Math.min(NOW.getTime() - DAY, monthsAgo(m).getTime()));
    if (to <= from) continue;
    const usage = Math.max(0, odoAt(to) - odoAt(from));
    const drift = 1 + (monthsSpan - m) * 0.002; // prices creep up slowly
    const at = (t) => new Date(from.getTime() + t * (to - from));

    // Energy
    const primaryShare = 1 - (f.petrolShare || 0) - (f.dcShare || 0);
    const needed = (usage * primaryShare) / f.efficiency;
    const unit = f.kind === 'cng' ? 'kg' : f.kind === 'charging' ? 'kWh' : 'L';
    const avgFill = (f.fillQty[0] + f.fillQty[1]) / 2;
    const fills = Math.min(10, Math.max(needed > 0 ? 1 : 0, Math.round(needed / avgFill)));
    for (let i = 0; i < fills; i += 1) {
      const date = at((i + between(0.2, 0.9)) / fills);
      const qty = needed / fills;
      entries.push(
        fuelEntry({
          owner,
          vehicle: vehicleId,
          date,
          odometer: odoAt(date),
          unit,
          qty,
          price: between(...f.price) * drift,
          vendor: pick(FUEL_VENDORS[f.kind]),
          category: f.kind === 'charging' ? 'charging' : 'fuel',
          fullTank: rand() < 0.6,
        })
      );
    }
    if (f.petrolShare) {
      const qty = (usage * f.petrolShare) / f.petrolEfficiency;
      if (qty > 2) {
        const date = at(between(0.3, 0.8));
        entries.push(fuelEntry({ owner, vehicle: vehicleId, date, odometer: odoAt(date), unit: 'L', qty, price: between(103, 106.5) * drift, vendor: pick(FUEL_VENDORS.petrol), category: 'fuel', fullTank: false }));
      }
    }
    if (f.dcShare) {
      const kwh = (usage * f.dcShare) / f.efficiency;
      const sessions = Math.max(1, Math.round(kwh / 28));
      for (let i = 0; i < sessions; i += 1) {
        const date = at(between(0.1, 0.95));
        entries.push(fuelEntry({ owner, vehicle: vehicleId, date, odometer: odoAt(date), unit: 'kWh', qty: kwh / sessions, price: between(...f.dcPrice), vendor: pick(FUEL_VENDORS.dc), category: 'charging', fullTank: false }));
      }
    }

    // Tolls, parking, cleaning
    const tolls = randInt(...x.tollsPerMonth);
    for (let i = 0; i < tolls; i += 1) {
      entries.push({
        owner,
        vehicle: vehicleId,
        category: 'toll',
        amount: roundTo(between(90, 480), 5),
        date: at(between(0, 1)),
        description: 'FASTag toll',
        vendor: pick(['Khed Shivapur Toll Plaza', 'Talegaon Toll Plaza', 'Urse Toll Plaza', 'Saswad Road Toll']),
        paymentMethod: 'wallet',
      });
    }
    if (x.parking) {
      entries.push({ owner, vehicle: vehicleId, category: 'parking', amount: roundTo(x.parking * between(0.6, 1.4), 10), date: at(between(0.2, 0.9)), description: pick(['Mall parking', 'Office parking', 'Airport parking', 'Railway station parking']), paymentMethod: 'upi' });
    }
    if (x.cleaning) {
      entries.push({ owner, vehicle: vehicleId, category: 'cleaning', amount: roundTo(x.cleaning * between(0.8, 1.3), 10), date: at(between(0.3, 0.95)), description: pick(['Car wash & vacuum', 'Foam wash', 'Interior detailing', 'Doorstep wash']), vendor: 'Sparkle Car Spa', paymentMethod: 'upi' });
    }
  }

  // Insurance premiums follow the insurance documents' issue dates.
  for (const doc of def.docs.filter((d) => d.type === 'insurance')) {
    for (const back of [0, 365]) {
      const date = new Date(NOW.getTime() - (doc.issuedDaysAgo + back) * DAY);
      if (date < windowStart) continue;
      entries.push({ owner, vehicle: vehicleId, category: 'insurance', amount: roundTo(x.insurance * (back ? 0.94 : 1), 10), date, description: `Insurance premium · ${doc.number}`, vendor: doc.issuer, paymentMethod: 'card' });
    }
  }
  for (const doc of def.docs.filter((d) => d.type === 'pollution_certificate')) {
    const date = new Date(NOW.getTime() - doc.issuedDaysAgo * DAY);
    if (date >= windowStart) entries.push({ owner, vehicle: vehicleId, category: 'registration', amount: def.vehicle.fuelType === 'diesel' ? 200 : 150, date, description: 'PUC certificate renewal', vendor: doc.issuer, paymentMethod: 'cash' });
  }
  if (x.roadTax) {
    entries.push({ owner, vehicle: vehicleId, category: 'taxes', amount: x.roadTax, date: monthsAgo(8), description: 'Annual goods vehicle tax', vendor: 'RTO Pimpri-Chinchwad', paymentMethod: 'net_banking' });
    entries.push({ owner, vehicle: vehicleId, category: 'registration', amount: x.permit, date: monthsAgo(14), description: 'Permit authorisation fee', vendor: 'State Transport Authority', paymentMethod: 'net_banking' });
  }
  return entries;
}

const ONE_OFF_EXPENSES = {
  glanza: [{ category: 'accessories', amount: 5500, monthsAgo: 15, description: 'Premium seat covers', vendor: 'Autoform Pune' }],
  creta: [
    { category: 'accessories', amount: 6499, monthsAgo: 13, description: 'Dashcam (front + rear)', vendor: 'Croma, Wakad' },
    { category: 'repairs', amount: 1800, monthsAgo: 5, description: 'Windshield chip repair', vendor: 'GlassFix Pune' },
  ],
  nexon: [
    { category: 'accessories', amount: 3200, monthsAgo: 16, description: '3D floor mats', vendor: 'Tata Motors Accessories' },
    { category: 'accessories', amount: 18500, monthsAgo: 17, description: 'Wallbox installation (7.2 kW)', vendor: 'Home EV Solutions' },
  ],
  classic: [{ category: 'accessories', amount: 4800, monthsAgo: 10, description: 'Touring seat & saddle stays', vendor: 'RE Genuine Accessories' }],
  activa: [{ category: 'accessories', amount: 2100, monthsAgo: 6, description: 'ISI helmet', vendor: 'Steelbird Store' }],
  ola: [{ category: 'repairs', amount: 950, monthsAgo: 2, description: 'Side mirror replacement', vendor: 'Ola Experience Centre' }],
  ace: [
    { category: 'parts', amount: 5200, monthsAgo: 3, description: 'Battery replacement (12V 65Ah)', vendor: 'Amaron Battery Point' },
    { category: 'repairs', amount: 150, monthsAgo: 1.2, description: 'Puncture repair', vendor: 'Roadside tyre shop' },
    { category: 'repairs', amount: 2400, monthsAgo: 0.6, description: 'Clutch cable replacement', vendor: 'Balaji Auto Works' },
  ],
  tractor: [
    { category: 'parts', amount: 4800, monthsAgo: 11, description: 'Rotavator blade set', vendor: 'Kisan Agro Parts' },
    { category: 'parts', amount: 1350, monthsAgo: 4, description: 'Hydraulic hose', vendor: 'Kisan Agro Parts' },
  ],
};

// ─── Demo fleet ──────────────────────────────────────────────────────────────
async function seedDemoFleet(user) {
  step('Simulating demo fleet history (this replays ~18 months through the scheduling engine)');
  let invoiceCounter = 1200;
  const summary = [];

  for (const def of demoFleet) {
    const odoAt = buildUsageModel(def);
    const baselineDate = monthsAgo(def.baselineMonthsAgo);
    const baselineOdo = odoAt(baselineDate);

    const vehicle = await Vehicle.create({
      ...def.vehicle,
      owner: user._id,
      purchaseDate: new Date(def.vehicle.purchaseDate),
      purchaseOdometer: def.vehicle.purchaseOdometer || 0,
      odometer: baselineOdo,
      odometerUpdatedAt: baselineDate,
      odometerLogs: [],
    });

    // Tracking starts with a full service at the baseline.
    await syncSchedule(vehicle, {
      now: baselineDate,
      baseline: { date: baselineDate, odometer: baselineOdo, estimated: false },
      notifyAlerts: false,
    });

    for (const h of def.taskHistory || []) {
      const task = await MaintenanceTask.findOne({ vehicle: vehicle._id, code: h.code, isOpen: true });
      if (!task) continue;
      task.lastPerformedDate = new Date(NOW.getTime() - h.daysAgo * DAY);
      task.lastPerformedOdometer = odoAt(task.lastPerformedDate);
      Object.assign(task, computeNextDue(task));
      await task.save();
    }

    // Timeline of service visits + monthly DIY checks.
    const events = def.services.map((s) => ({ kind: 'service', at: monthsAgo(s.monthsAgo), s }));
    for (let m = def.baselineMonthsAgo - 0.8; m > 0.15; m -= 1) {
      if (def.key === 'ace' && m < 3) continue; // the delivery van has been neglected lately
      events.push({ kind: 'diy', at: monthsAgo(m) });
    }
    events.sort((a, b) => a.at - b.at);

    let services = 0;
    let completed = 0;
    let lastRecord = null;
    for (const e of events) {
      if (e.kind === 'service') {
        invoiceCounter += randInt(7, 40);
        const r = await simulateService(user._id, vehicle, def, e.s, odoAt, invoiceCounter);
        services += 1;
        completed += r.completed;
        lastRecord = r;
      } else {
        completed += await simulateDiy(user._id, vehicle, e.at, odoAt(e.at));
      }
    }

    // Running costs and one-off purchases.
    const expenses = runningCosts(user._id, vehicle._id, def, odoAt, baselineDate);
    for (const o of ONE_OFF_EXPENSES[def.key] || []) {
      const date = monthsAgo(o.monthsAgo);
      expenses.push({ owner: user._id, vehicle: vehicle._id, paymentMethod: 'card', odometer: odoAt(date), ...o, date });
    }
    await Expense.insertMany(expenses.map(({ monthsAgo: _m, ...e }) => e));

    // Odometer history: monthly readings since purchase + today.
    const logs = [];
    const purchase = new Date(def.vehicle.purchaseDate);
    for (let d = new Date(purchase); d < NOW; d = addMonths(d, 1)) logs.push({ value: odoAt(d), date: new Date(d), source: 'manual' });
    logs.push({ value: def.currentOdometer, date: NOW, source: 'manual' });
    await Vehicle.updateOne(
      { _id: vehicle._id },
      {
        $set: {
          odometer: def.currentOdometer,
          odometerUpdatedAt: new Date(NOW.getTime() - randInt(1, 4) * DAY),
          odometerLogs: logs.slice(-400),
          ...(lastRecord ? { lastServiceDate: lastRecord.date, lastServiceOdometer: lastRecord.odometer } : {}),
        },
      }
    );
    await Vehicle.collection.updateOne({ _id: vehicle._id }, { $set: { createdAt: baselineDate } });

    // Documents (+ automatic expiry reminders).
    for (const d of def.docs) {
      const issueDate = new Date(NOW.getTime() - d.issuedDaysAgo * DAY);
      const expiryDate = d.expiresInDays !== undefined ? daysFromNow(d.expiresInDays) : null;
      const buffer = await documentPdf({
        title: d.name,
        issuer: d.issuer,
        number: d.number,
        holder: user.name,
        vehicle: `${def.vehicle.make} ${def.vehicle.model} · ${def.vehicle.registrationNumber}`,
        issueDate,
        expiryDate,
      });
      const file = await uploadBuffer(buffer, {
        originalName: `${d.name.replace(/[^a-z0-9]+/gi, '-')}.pdf`,
        mimeType: 'application/pdf',
        folder: 'documents',
      });
      const doc = new Document({
        owner: user._id,
        vehicle: vehicle._id,
        name: d.name,
        type: d.type,
        documentNumber: d.number,
        issuer: d.issuer,
        issueDate,
        expiryDate,
        uploadDate: issueDate > baselineDate ? issueDate : baselineDate,
        reminderDaysBefore: d.reminderDays || 30,
        file,
      });
      await doc.save();
      await syncDocumentReminder(doc);
      await doc.save();
    }

    await refreshVehicle(vehicle._id, { notifyAlerts: true });
    const fresh = await Vehicle.findById(vehicle._id).lean();
    summary.push({
      vehicle: `${def.vehicle.make} ${def.vehicle.model}`,
      odometer: `${def.currentOdometer.toLocaleString('en-IN')} ${unitFor(def.vehicle.vehicleType)}`,
      services,
      itemsCompleted: completed,
      expenses: expenses.length,
      openItems: fresh.openTaskCounts.total,
      overdue: fresh.openTaskCounts.overdue,
      due: fresh.openTaskCounts.due,
      dueSoon: fresh.openTaskCounts.dueSoon,
      health: `${fresh.healthScore} (${fresh.healthLabel})`,
    });
  }
  console.table(summary);
}

async function seedPersonalItems(user) {
  step('Adding personal documents and custom reminders');
  const vehicles = await Vehicle.find({ owner: user._id }).select('model').lean();
  const byModel = (m) => vehicles.find((v) => v.model.includes(m))?._id;

  const licenceExpiry = daysFromNow(610);
  const licence = new Document({
    owner: user._id,
    vehicle: null,
    name: 'Driving Licence',
    type: 'driving_license',
    documentNumber: 'MH12 20150034567',
    issuer: 'RTO Pune',
    issueDate: new Date(NOW.getTime() - 3400 * DAY),
    expiryDate: licenceExpiry,
    reminderDaysBefore: 60,
    file: await uploadBuffer(
      await documentPdf({ title: 'Driving Licence (LMV, MCWG)', issuer: 'RTO Pune', number: 'MH12 20150034567', holder: user.name, issueDate: new Date(NOW.getTime() - 3400 * DAY), expiryDate: licenceExpiry }),
      { originalName: 'Driving-Licence.pdf', mimeType: 'application/pdf', folder: 'documents' }
    ),
  });
  await licence.save();
  await syncDocumentReminder(licence);
  await licence.save();

  await Reminder.insertMany([
    { owner: user._id, vehicle: byModel('Creta'), type: 'custom', title: 'Renew FASTag KYC', description: 'Bank requested updated KYC for the FASTag wallet.', dueDate: daysFromNow(10), remindBeforeDays: 15, source: 'manual' },
    { owner: user._id, vehicle: byModel('575'), type: 'custom', title: 'Pre-season check before Rabi sowing', description: 'Rotavator, hydraulics and tyres before the season starts.', dueDate: daysFromNow(20), remindBeforeDays: 30, source: 'manual' },
    { owner: user._id, vehicle: byModel('Glanza'), type: 'custom', title: 'Monthly car wash subscription', description: 'Renew the doorstep wash plan.', dueDate: daysFromNow(4), remindBeforeDays: 7, repeat: 'monthly', source: 'manual' },
    { owner: user._id, vehicle: byModel('Ace'), type: 'custom', title: 'GPS tracker subscription renewal', description: 'Quarterly fleet-tracking plan for the delivery vehicle.', dueDate: daysFromNow(-3), remindBeforeDays: 7, repeat: 'none', source: 'manual' },
    { owner: user._id, vehicle: byModel('Creta'), type: 'custom', title: 'Wheel alignment after Goa trip', description: 'Steering pulled slightly left on the ghats.', dueDate: monthsAgo(2.2), remindBeforeDays: 3, status: 'completed', completedAt: monthsAgo(2.1), source: 'manual' },
  ]);
}

async function polishNotifications(user) {
  await processDueReminders();
  await Notification.insertMany([
    { user: user._id, type: 'system', severity: 'success', title: 'Welcome to AutoCare360 🎉', message: 'Your garage is ready. Maintenance schedules are generated automatically for each vehicle.', link: '/app', read: true, readAt: NOW },
    { user: user._id, type: 'service', severity: 'success', title: 'Service record saved', message: 'Toyota Glanza periodic service recorded — schedule updated.', link: '/app/service-history', read: true, readAt: NOW },
  ]);
  // Spread notifications over the last fortnight so the notification centre looks natural.
  const all = await Notification.find({ user: user._id }).select('_id severity').lean();
  for (const n of all) {
    const hoursAgo = n.severity === 'critical' ? between(1, 60) : between(2, 340);
    const createdAt = new Date(NOW.getTime() - hoursAgo * 3600000);
    const read = hoursAgo > 72 && rand() < 0.7;
    await Notification.collection.updateOne({ _id: n._id }, { $set: { createdAt, updatedAt: createdAt, read, ...(read ? { readAt: createdAt } : {}) } });
  }
  info(`${all.length} notifications in the demo notification centre`);
}

// ─── Other platform users (admin panel realism) ─────────────────────────────
async function seedExtraUsers() {
  step('Creating additional platform users');
  for (const u of extraUsers) {
    const joined = monthsAgo(u.joinedMonthsAgo);
    const user = await User.create({
      name: u.name,
      email: u.email,
      password: 'Welcome@123',
      isActive: !u.blocked,
      blockedReason: u.blocked,
      lastLoginAt: new Date(NOW.getTime() - between(0.2, 20) * DAY),
    });
    await User.collection.updateOne({ _id: user._id }, { $set: { createdAt: joined } });

    for (const spec of u.vehicles) {
      const hours = unitFor(spec.vehicleType) === 'hrs';
      const lastServiceDate = new Date(NOW.getTime() - between(40, 260) * DAY);
      const lastServiceOdometer = Math.max(0, spec.odometer - Math.round(hours ? between(80, 300) : between(2500, 9000)));
      const vehicle = await Vehicle.create({
        ...spec,
        owner: user._id,
        purchaseDate: new Date(`${spec.year}-0${randInt(1, 9)}-1${randInt(0, 9)}`),
        lastServiceDate,
        lastServiceOdometer,
        odometerLogs: [
          { value: lastServiceOdometer, date: lastServiceDate, source: 'service' },
          { value: spec.odometer, date: NOW, source: 'manual' },
        ],
      });
      await syncSchedule(vehicle, { notifyAlerts: false });
      await Vehicle.collection.updateOne({ _id: vehicle._id }, { $set: { createdAt: new Date(joined.getTime() + between(0, 10) * DAY) } });

      const total = roundTo(between(2500, 14000));
      const record = await ServiceRecord.create({
        owner: user._id,
        vehicle: vehicle._id,
        serviceDate: lastServiceDate,
        odometer: lastServiceOdometer,
        serviceCenter: `${spec.make} Authorised Service`,
        serviceType: 'periodic_service',
        maintenanceItems: [{ name: 'General service' }, { name: 'Oil & filter change' }],
        laborCost: roundTo(total * 0.35),
        partsCost: roundTo(total * 0.5),
        taxes: roundTo(total * 0.15),
      });
      const expense = await Expense.create({ owner: user._id, vehicle: vehicle._id, category: 'maintenance', amount: record.totalCost, date: lastServiceDate, serviceRecord: record._id, description: 'Periodic service' });
      record.expense = expense._id;
      await record.save();
      for (let i = 0; i < randInt(3, 7); i += 1) {
        await Expense.create({
          owner: user._id,
          vehicle: vehicle._id,
          category: spec.fuelType === 'electric' ? 'charging' : 'fuel',
          amount: roundTo(between(400, 4500)),
          date: new Date(NOW.getTime() - between(1, 120) * DAY),
          description: spec.fuelType === 'electric' ? 'Charging' : 'Fuel',
        });
      }
    }
    info(`${u.name}${u.blocked ? ' (blocked)' : ''} — ${u.vehicles.length} vehicle(s)`);
  }
}

// ─── Main ────────────────────────────────────────────────────────────────────
async function clearUploads() {
  if (isCloudinaryEnabled) return;
  const entries = await fs.readdir(UPLOAD_ROOT, { withFileTypes: true }).catch(() => []);
  await Promise.all(
    entries.filter((e) => e.isDirectory()).map((e) => fs.rm(path.join(UPLOAD_ROOT, e.name), { recursive: true, force: true }))
  );
}

async function main() {
  const started = Date.now();
  await connectDB();

  if (CATALOG_ONLY) {
    await seedCatalog();
    await Promise.all([VehicleType, FuelType, MaintenanceCategory, MaintenanceTemplate].map((m) => m.syncIndexes()));
    console.log('\n✔ Catalog loaded.');
    return;
  }

  step('Resetting database');
  await mongoose.connection.dropDatabase();
  await clearUploads();
  const models = [User, VehicleType, FuelType, MaintenanceCategory, MaintenanceTemplate, Vehicle, MaintenanceTask, ServiceRecord, Expense, Document, Reminder, Notification];
  await Promise.all(models.map((m) => m.syncIndexes()));

  await seedCatalog();

  step('Creating demo & admin accounts');
  // Admin sign-in can be set per environment (SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD in server/.env).
  const adminUser = {
    ...ADMIN_USER,
    email: (process.env.SEED_ADMIN_EMAIL || ADMIN_USER.email).trim().toLowerCase(),
    password: process.env.SEED_ADMIN_PASSWORD || ADMIN_USER.password,
  };
  const admin = await User.create({ ...adminUser, lastLoginAt: NOW });
  await User.collection.updateOne({ _id: admin._id }, { $set: { createdAt: monthsAgo(20) } });
  const demo = await User.create({ ...DEMO_USER, lastLoginAt: NOW });
  await User.collection.updateOne({ _id: demo._id }, { $set: { createdAt: monthsAgo(18.5) } });
  info(`Demo:  ${DEMO_USER.email} / ${DEMO_USER.password}`);
  info(`Admin: ${adminUser.email} / ${adminUser.password}`);

  await seedDemoFleet(demo);
  await seedPersonalItems(demo);
  await polishNotifications(demo);
  await seedExtraUsers();
  await User.updateMany({}, { $set: { lastStatusSyncAt: new Date() } });

  const counts = await Promise.all(models.map(async (m) => [m.modelName, await m.countDocuments()]));
  step('Done');
  console.table(Object.fromEntries(counts));
  console.log(`\n✔ Seed completed in ${((Date.now() - started) / 1000).toFixed(1)}s`);
  console.log(`  Sign in → ${DEMO_USER.email} / ${DEMO_USER.password}   (admin: ${adminUser.email} / ${adminUser.password})\n`);
}

main()
  .catch((error) => {
    console.error('\n✖ Seed failed:', error);
    process.exitCode = 1;
  })
  .finally(() => mongoose.disconnect());
